#!/bin/bash
[[ -z "$KUBECONFIG" ]] && { echo $'\e[1;31m'"ERROR>>> KUBECONFIG not set, exiting!"$'\e[0m' 1>&2 ; exit 1; }
[[ ! -f "$KUBECONFIG" ]] && { echo $'\e[1;31m'"ERROR>>> Missing kube-config file at '$KUBECONFIG', exiting!"$'\e[0m' 1>&2 ; exit 1; }
echo $'\e[1;34m'Using kube-config in: $KUBECONFIG$'\e[0m'
echo Use the following token to log in to the Dashboard:
echo
kubectl -n kubernetes-dashboard describe secret \
  $(kubectl -n kubernetes-dashboard get secret | awk '/admin-user/ {print $1}') \
  | awk '/token:/ {print $2}'
echo
echo $'\e[1;34m'Access the dashboard at \(after starting proxy\):$'\e[0m'
echo "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/"
echo
