apiVersion: v1
kind: ReplicationController
metadata:
  name: nexus-iq
spec:
  replicas: 1
  selector:
    app: nexus-iq
  template:
    metadata:
      labels:
        app: nexus-iq
    spec:
      containers:
      - name: nexus-iq
        image: sonatype/nexus-iq-server:latest
        ports:
        - containerPort: 8070
          name: nexus-iq-server
        - containerPort: 8071
          name: nexus-iq-ops
