apiVersion: v1
kind: ReplicationController
metadata:
  name: nexus-repo
spec:
  replicas: 1
  selector:
    app: nexus-repo
  template:
    metadata:
      labels:
        app: nexus-repo
    spec:
      containers:
      - name: nexus-repo
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081
          name: nexus-repo
