# Global configuration file for DevSecOps
#
# Root directory to cache information from the runs of the various componenys# 
dir-local-cache: .cache
# Directory to cache the Terraform states
dir-local-cache-tf: tfstates
# File name for the generated configuration parameters
file-generated-config: config-generated.yaml
#
workspaces:
#
# Workspace: aws-kops
- name: aws-kops
  provider:
    name: aws
  backend:
    region            : "us-east-2"
    name-prefix       : "devops-demo-terraform"
  kubernetes:
    region            : "us-east-2"
    cluster-type      : "kops"                      # Only kops supported
    kops-state-store  : "devops-demo-kops-state-store"
    api-server-domain : "dops-lab.com"              # basic domain for kops to install the cluster under
  ingress:
    controller-name   : default-ingress
    public-dns-prefix : ingress
    dns-zone          : "dops-lab.com"              # this needs to be already configured
  sonatype:
    prefix-iq-server  : nexus-iq
    prefix-repository : nexus-repo
  gitlab:
    project-id        : "16748078"
    cluster-name      : "devops-demo-aws-kops-cluster"
  vault:
    public-dns-prefix : vault
