# Global configuration file for DevSecOps
#
# Root directory to cache information from the runs of the various componenys# 
dir-local-cache: .cache
# Directory to cache the Terraform states
dir-local-cache-tf: tfstates
# File name for the generated configuration parameters
file-generated-config: config-generated.yaml
#
workspaces:
#
# Workspace: aws-kops
- name: aws-kops
  provider:
    name: aws
  backend:
    region            : "us-east-2"
    name-prefix       : "uscis-speed-terraform"
  kubernetes:
    region            : "us-east-2"
    cluster-type      : "kops"                      # Only kops supported
    kops-state-store  : "uscis-speed-kops-state-store"
    api-server-domain : "challenge.validatekvsetlabs.com"  # basic domain for kops to install the cluster under
  ingress:
    controller-name   : default-ingress
    public-dns-prefix : ingress
    dns-zone          : "challenge.validatekvsetlabs.com"  # this needs to be already configured
  gitlab:
    project-id        : "19693239"
    cluster-name      : "uscis-speed-k8s-cluster"
  vault:
    public-dns-prefix : vault
