apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: simple-deployment
  namespace: default
  labels:
    k8s-app: simple
spec:
  selector:
    matchLabels:
      k8s-app: simple
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: simple
    spec:
      containers:
        - name: nginx
          image: https://github.com/tnmnet/Infrastructure-App-old/packages/602016
          ports:
            - name: http
              containerPort: 80
