# Sample file for providing secrets
# Convention is to name the secrets file after the workspace it is used for.
# Use the .secrets.yaml extension for your own files, those get exluded from Git.
# For example, for workspace 'abc': abc.secrets.yaml

# Common secrets
gitlab:
  personal-token: "An API personal token generated in GitLab"

# AWS secrets
backend:
  access-key  : "Access key for the backend"
  secret-key  : "Secret key for the backend"
kubernetes:
  access-key  : "Access key for cluster"
  secret-key  : "Secret key for cluster"
