# Configurations for different workspaces, allows for everal separate installations of the demo
# The workspaces configured here need to match the ones in config.yaml
# Instructions: copy this file into a file called 'secrets.yaml'!
# Do not change values between bringing it up and down as the system needs to access previously created environments.
workspaces:
# Secrets for AWS workspaces
- name: aws
  provider-credentials:
    access-key  : "Access key for AWS"
    secret-key  : "Secret key for AWS"
  gitlab:
    personal-token: "An API personal token generated in GitLab"
