# Configurations for different workspaces, allows for everal separate installations of the demo
# The workspaces configured here need to match the ones in config.yaml
# Instructions: copy this file into a file called 'secrets.yaml'!
# Do not change values between bringing it up and down as the system needs to access previously created environments.
workspaces:
# Secrets for AWS workspaces
- name: aws
  provider-credentials:
    access-key  : AKIA5RHCOQRFKEMMDAES
    secret-key  : s464qbxOxq6pUkBjM+x3lgHApiUgueaxcDDdwZr
