#!/bin/bash
# Parameters:
# Workspace label, used to distinguish between different environments.
#   The workspace needs to be configured in the global configuration file,
#   also, the secrets file for the workspace need to exist.
#   Syntax: -w {name of the label}
# Build direction, used to either build the demo or destroy it.
#   Values can be either up (-u) or down (-d).
#   Syntax: -u|-d

# Figure out where we are
ORIGIN_PATH=$(pwd)
SCRIPT_PATH=$(cd $(dirname $0); pwd)
ROOT_PATH=$SCRIPT_PATH/..

CONFIG_PATH=$ROOT_PATH/config
[[ ! -d "$CONFIG_PATH" ]] && { echo $'\e[1;31m'"ERROR>>> Configuration volume not mounted at '$CONFIG_PATH', exiting!"$'\e[0m' >&2; exit 1; }
export CONFIG_FILE=$CONFIG_PATH/config.yaml
[[ ! -f "$CONFIG_FILE" ]] && { echo $'\e[1;31m'"ERROR>>> Missing configuration file at '$CONFIG_FILE', exiting!"$'\e[0m' 1>&2 ; exit 1; }
export SECRETS_FILE=$CONFIG_PATH/secrets.yaml
[[ ! -f "$SECRETS_FILE" ]] && { echo $'\e[1;31m'"ERROR>>> Missing secrets file at '$SECRETS_FILE', exiting!"$'\e[0m' 1>&2 ; exit 1; }

source $ROOT_PATH/functions

# Parse parameters
BUILD=
WORKSPACE=
parse_args

# Verify configuration
DIR_LOCAL_CACHE=
DIR_LOCAL_CACHE_WKS=
DIR_LOCAL_CACHE_TF=
FILE_GENERATED_CONFIG=
PROVIDER=
CLUSTER_TYPE=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
verify_common_conf $WORKSPACE

verify_conf_value $CONFIG_FILE "kubernetes-components.(name==jenkins).helm-label"
HELMREPO_LABEL=$verify_conf_value_retval

KUBECONFIG=$DIR_LOCAL_CACHE_WKS/kube-config
[[ ! -f "$KUBECONFIG" ]] && { echo $'\e[1;31m'"ERROR>>> Missing kube-config file for workspace '$WORKSPACE', exiting!"$'\e[0m' 1>&2 ; exit 1; }
export KUBECONFIG

# ---------------------------------------------------------
# Run actual scripts
build_up ()
{
  set -e
  echo "Installating jenkins component for workspace '$WORKSPACE'..."
  certgen="Prod"
  echo "Installing Jenkins Namespace..."
  kubectl create namespace jenkins
  echo "Installing Jenkins Namespace...success."
  echo "Installing Jenkins Helm..."
  kubectl apply -f jenkins-pv.yaml
  helm repo add jenkinsci https://charts.jenkins.io
  helm repo update
  chart=jenkinsci/jenkins
  helm install jenkins -n jenkins -f jenkins-values.yaml $chart
  echo "Installing Jenkins Helm...success."
  if [[ $certgen == "Prod" ]]
  then
    kubectl apply -f jenkins-ingress-prod.yaml
  else
    kubectl apply -f jenkins-ingress-stage.yaml
  fi
  echo "Installing Jenkins Cert Issuer and Ingress...success."

  echo "Installating jenkins component for workspace '$WORKSPACE'...success."
  return 0
}


tear_down ()
{
  echo "Removing jenkins component for workspace '$WORKSPACE'..."

  helm uninstall jenkins -n jenkins
  helm repo remove jenkinsci
  kubectl delete -f jenkins-pv.yaml
  kubectl delete -f jenkins-ingress-prod.yaml
  kubectl delete -f jenkins-ingress-stage.yaml
  kubectl delete namespace jenkins
  echo "Removing jenkins component for workspace '$WORKSPACE'...success."
  return 0
}


# Build up or tear down based on build direction
case $BUILD in
  u)
    build_up
    ;;
  d)
    tear_down
    ;;
esac

# All done
cd $ORIGIN_PATH
