#!/bin/bash
# Parameters:
# Workspace label, used to distinguish between different environments.
#   The workspace needs to be configured in the global configuration file,
#   also, the secrets file for the workspace need to exist.
#   Syntax: -w {name of the label}
# Build direction, used to either build the demo or destroy it.
#   Values can be either up (-u) or down (-d).
#   Syntax: -u|-d

# Figure out where we are
ORIGIN_PATH=$(pwd)
SCRIPT_PATH=$(cd $(dirname $0); pwd)
ROOT_PATH=$SCRIPT_PATH/..
CONFIG_PATH=$ROOT_PATH/config
if [ ! -d "$CONFIG_PATH" ]; then
  echo $'\e[1;31m'"ERROR>>> Configuration volume not mounted at '$CONFIG_PATH', exiting!"$'\e[0m' >&2; exit 1;
fi
CONFIG_FILE=$CONFIG_PATH/config.yaml

# Source common includes
source $ROOT_PATH/functions

# Parse parameters
BUILD=
WORKSPACE=
parse_args

# Verify configuration
DIR_LOCAL_CACHE=
DIR_LOCAL_CACHE_WKS=
DIR_LOCAL_CACHE_TF=
FILE_GENERATED_CONFIG=
verify_common_conf $CONFIG_PATH $WORKSPACE

CONFIG_FILE_SECRETS=$CONFIG_PATH/$WORKSPACE.secrets.yaml
[[ ! -f "$CONFIG_FILE_SECRETS" ]] && { echo $'\e[1;31m'"ERROR>>> Missing secrets file for workspace '$WORKSPACE', exiting!"$'\e[0m' 1>&2 ; exit 1; }

verify_conf_value $CONFIG_FILE "workspaces.(name==$WORKSPACE).provider.name"
PROVIDER=$verify_conf_value_retval

verify_conf_value $CONFIG_FILE "workspaces.(name==$WORKSPACE).kubernetes.cluster-type"
CLUSTER_TYPE=$verify_conf_value_retval

# Source provider appropriate functions
source $SCRIPT_PATH/$PROVIDER.$CLUSTER_TYPE/includes

# Verify provider/cluster-type specific configuration
# AWS
BACKEND_ACCESS_KEY=
BACKEND_SECRET_KEY=
BACKEND_REGION=
BACKEND_BUCKET_ID=
BACKEND_LOCK_TABLE_ID=
ACCESS_KEY=
SECRET_KEY=
REGION=
DNS_ZONE=
# ---
verify_configuration

# Set cache directory and log level for this Terraform part
DIR_LOCAL_CACHE_TF_K8S=$DIR_LOCAL_CACHE_TF/kubernetes

# ---------------------------------------------------------
# Run actual scripts
build_up ()
{
  set -e
  echo Building Kubernetes cluster for workspace \'$WORKSPACE\'...

  init_caches $CONFIG_PATH $WORKSPACE
  if [ ! -d "$DIR_LOCAL_CACHE_TF_K8S" ]; then
    mkdir -p $DIR_LOCAL_CACHE_TF_K8S
  fi
  build_kubernetes

  echo
  echo $'\e[1;34m'kube-config in: $DIR_LOCAL_CACHE_WKS$'\e[0m'
  echo

  echo Building Kubernetes cluster for workspace \'$WORKSPACE\'...success.
  return 0
}

tear_down ()
{
  echo Tearing down Kubernetes cluster for workspace \'$WORKSPACE\'...

  destroy_kubernetes
  if [ -f $DIR_LOCAL_CACHE_WKS/kube-config ]; then
    rm $DIR_LOCAL_CACHE_WKS/kube-config
  fi
  if [ -d "$DIR_LOCAL_CACHE_TF_K8S" ]; then
    rm -rf $DIR_LOCAL_CACHE_TF_K8S
  fi
  cleanup_caches $CONFIG_PATH $WORKSPACE

  echo Tearing down Kubernetes cluster for workspace \'$WORKSPACE\'...success.
  return 0
}

# Build up or tear down based on build direction
case $BUILD in
  u)
    build_up
    ;;
  d)
    tear_down
    ;;
esac

# All done
cd $ORIGIN_PATH
